#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 109
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_SEMI = 3,
  anon_sym_EQ = 4,
  aux_sym_identifier_token1 = 5,
  aux_sym_identifier_token2 = 6,
  anon_sym_DOT = 7,
  anon_sym_e = 8,
  anon_sym_E = 9,
  anon_sym__ = 10,
  sym__digit = 11,
  anon_sym_PLUS = 12,
  anon_sym_DASH = 13,
  anon_sym_0x = 14,
  sym__hex_digit = 15,
  anon_sym_0o = 16,
  aux_sym__octal_token1 = 17,
  aux_sym__octal_token2 = 18,
  anon_sym_0b = 19,
  anon_sym_0 = 20,
  anon_sym_1 = 21,
  anon_sym_false = 22,
  anon_sym_true = 23,
  sym_null = 24,
  sym__newline = 25,
  anon_sym_ = 26,
  sym__unicode_space = 27,
  anon_sym_BSLASH = 28,
  anon_sym_SLASH_SLASH = 29,
  aux_sym_single_line_comment_token1 = 30,
  sym_document = 31,
  sym_node = 32,
  sym__node_prop_or_arg = 33,
  sym__node_children = 34,
  sym__node_space = 35,
  sym__node_terminator = 36,
  sym_prop = 37,
  sym_identifier = 38,
  sym_value = 39,
  sym_number = 40,
  sym__decimal = 41,
  sym__exponent = 42,
  sym__integer = 43,
  sym__sign = 44,
  sym__hex = 45,
  sym__octal = 46,
  sym__binary = 47,
  sym_boolean = 48,
  sym__linespace = 49,
  sym__ws = 50,
  sym__escline = 51,
  sym_single_line_comment = 52,
  aux_sym_document_repeat1 = 53,
  aux_sym_node_repeat1 = 54,
  aux_sym_node_repeat2 = 55,
  aux_sym__node_space_repeat1 = 56,
  aux_sym__node_space_repeat2 = 57,
  aux_sym_identifier_repeat1 = 58,
  aux_sym__integer_repeat1 = 59,
  aux_sym__hex_repeat1 = 60,
  aux_sym__octal_repeat1 = 61,
  aux_sym__binary_repeat1 = 62,
  aux_sym_single_line_comment_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [aux_sym_identifier_token1] = "identifier_token1",
  [aux_sym_identifier_token2] = "identifier_token2",
  [anon_sym_DOT] = ".",
  [anon_sym_e] = "e",
  [anon_sym_E] = "E",
  [anon_sym__] = "_",
  [sym__digit] = "_digit",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_0x] = "0x",
  [sym__hex_digit] = "_hex_digit",
  [anon_sym_0o] = "0o",
  [aux_sym__octal_token1] = "_octal_token1",
  [aux_sym__octal_token2] = "_octal_token2",
  [anon_sym_0b] = "0b",
  [anon_sym_0] = "0",
  [anon_sym_1] = "1",
  [anon_sym_false] = "false",
  [anon_sym_true] = "true",
  [sym_null] = "null",
  [sym__newline] = "_newline",
  [anon_sym_] = "﻿",
  [sym__unicode_space] = "_unicode_space",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_single_line_comment_token1] = "single_line_comment_token1",
  [sym_document] = "document",
  [sym_node] = "node",
  [sym__node_prop_or_arg] = "_node_prop_or_arg",
  [sym__node_children] = "_node_children",
  [sym__node_space] = "_node_space",
  [sym__node_terminator] = "_node_terminator",
  [sym_prop] = "prop",
  [sym_identifier] = "identifier",
  [sym_value] = "value",
  [sym_number] = "number",
  [sym__decimal] = "_decimal",
  [sym__exponent] = "_exponent",
  [sym__integer] = "_integer",
  [sym__sign] = "_sign",
  [sym__hex] = "_hex",
  [sym__octal] = "_octal",
  [sym__binary] = "_binary",
  [sym_boolean] = "boolean",
  [sym__linespace] = "_linespace",
  [sym__ws] = "_ws",
  [sym__escline] = "_escline",
  [sym_single_line_comment] = "single_line_comment",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_node_repeat1] = "node_repeat1",
  [aux_sym_node_repeat2] = "node_repeat2",
  [aux_sym__node_space_repeat1] = "_node_space_repeat1",
  [aux_sym__node_space_repeat2] = "_node_space_repeat2",
  [aux_sym_identifier_repeat1] = "identifier_repeat1",
  [aux_sym__integer_repeat1] = "_integer_repeat1",
  [aux_sym__hex_repeat1] = "_hex_repeat1",
  [aux_sym__octal_repeat1] = "_octal_repeat1",
  [aux_sym__binary_repeat1] = "_binary_repeat1",
  [aux_sym_single_line_comment_repeat1] = "single_line_comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [aux_sym_identifier_token2] = aux_sym_identifier_token2,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_E] = anon_sym_E,
  [anon_sym__] = anon_sym__,
  [sym__digit] = sym__digit,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_0x] = anon_sym_0x,
  [sym__hex_digit] = sym__hex_digit,
  [anon_sym_0o] = anon_sym_0o,
  [aux_sym__octal_token1] = aux_sym__octal_token1,
  [aux_sym__octal_token2] = aux_sym__octal_token2,
  [anon_sym_0b] = anon_sym_0b,
  [anon_sym_0] = anon_sym_0,
  [anon_sym_1] = anon_sym_1,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_true] = anon_sym_true,
  [sym_null] = sym_null,
  [sym__newline] = sym__newline,
  [anon_sym_] = anon_sym_,
  [sym__unicode_space] = sym__unicode_space,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_single_line_comment_token1] = aux_sym_single_line_comment_token1,
  [sym_document] = sym_document,
  [sym_node] = sym_node,
  [sym__node_prop_or_arg] = sym__node_prop_or_arg,
  [sym__node_children] = sym__node_children,
  [sym__node_space] = sym__node_space,
  [sym__node_terminator] = sym__node_terminator,
  [sym_prop] = sym_prop,
  [sym_identifier] = sym_identifier,
  [sym_value] = sym_value,
  [sym_number] = sym_number,
  [sym__decimal] = sym__decimal,
  [sym__exponent] = sym__exponent,
  [sym__integer] = sym__integer,
  [sym__sign] = sym__sign,
  [sym__hex] = sym__hex,
  [sym__octal] = sym__octal,
  [sym__binary] = sym__binary,
  [sym_boolean] = sym_boolean,
  [sym__linespace] = sym__linespace,
  [sym__ws] = sym__ws,
  [sym__escline] = sym__escline,
  [sym_single_line_comment] = sym_single_line_comment,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_node_repeat1] = aux_sym_node_repeat1,
  [aux_sym_node_repeat2] = aux_sym_node_repeat2,
  [aux_sym__node_space_repeat1] = aux_sym__node_space_repeat1,
  [aux_sym__node_space_repeat2] = aux_sym__node_space_repeat2,
  [aux_sym_identifier_repeat1] = aux_sym_identifier_repeat1,
  [aux_sym__integer_repeat1] = aux_sym__integer_repeat1,
  [aux_sym__hex_repeat1] = aux_sym__hex_repeat1,
  [aux_sym__octal_repeat1] = aux_sym__octal_repeat1,
  [aux_sym__binary_repeat1] = aux_sym__binary_repeat1,
  [aux_sym_single_line_comment_repeat1] = aux_sym_single_line_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [sym__digit] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0x] = {
    .visible = true,
    .named = false,
  },
  [sym__hex_digit] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_0o] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__octal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__octal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_0b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [sym__unicode_space] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_single_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_node] = {
    .visible = true,
    .named = true,
  },
  [sym__node_prop_or_arg] = {
    .visible = false,
    .named = true,
  },
  [sym__node_children] = {
    .visible = false,
    .named = true,
  },
  [sym__node_space] = {
    .visible = false,
    .named = true,
  },
  [sym__node_terminator] = {
    .visible = false,
    .named = true,
  },
  [sym_prop] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym__decimal] = {
    .visible = false,
    .named = true,
  },
  [sym__exponent] = {
    .visible = false,
    .named = true,
  },
  [sym__integer] = {
    .visible = false,
    .named = true,
  },
  [sym__sign] = {
    .visible = false,
    .named = true,
  },
  [sym__hex] = {
    .visible = false,
    .named = true,
  },
  [sym__octal] = {
    .visible = false,
    .named = true,
  },
  [sym__binary] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym__linespace] = {
    .visible = false,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [sym__escline] = {
    .visible = false,
    .named = true,
  },
  [sym_single_line_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_node_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_node_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__node_space_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__node_space_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__integer_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__hex_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__octal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__binary_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_single_line_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == ' ') ADVANCE(48);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '0') ADVANCE(41);
      if (lookahead == '1') ADVANCE(42);
      if (lookahead == ';') ADVANCE(20);
      if (lookahead == '=') ADVANCE(21);
      if (lookahead == 'E') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead == '_') ADVANCE(30);
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == 65279) ADVANCE(47);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'F')) ADVANCE(36);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      if (('2' <= lookahead && lookahead <= '7')) ADVANCE(26);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == ' ') ADVANCE(48);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '0') ADVANCE(32);
      if (lookahead == ';') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead == 'f') ADVANCE(23);
      if (lookahead == 'n') ADVANCE(25);
      if (lookahead == 't') ADVANCE(24);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == 65279) ADVANCE(47);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == ' ') ADVANCE(48);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == ';') ADVANCE(20);
      if (lookahead == 'E') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead == '_') ADVANCE(30);
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == 65279) ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == ' ') ADVANCE(48);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == ';') ADVANCE(20);
      if (lookahead == '=') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == 65279) ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == ' ') ADVANCE(48);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == ';') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead == '_') ADVANCE(30);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == 65279) ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == ' ') ADVANCE(48);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == ';') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == 65279) ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(50);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(45);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(38);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == ' ') ADVANCE(48);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '0') ADVANCE(41);
      if (lookahead == '1') ADVANCE(42);
      if (lookahead == ';') ADVANCE(20);
      if (lookahead == '=') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead == '_') ADVANCE(30);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == 65279) ADVANCE(47);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_E);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__digit);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__digit);
      if (lookahead == 'b') ADVANCE(40);
      if (lookahead == 'o') ADVANCE(37);
      if (lookahead == 'x') ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_0x);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__hex_digit);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_0o);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__octal_token1);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__octal_token2);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_0b);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_1);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__unicode_space);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_single_line_comment_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 16},
  [18] = {.lex_state = 16},
  [19] = {.lex_state = 16},
  [20] = {.lex_state = 16},
  [21] = {.lex_state = 16},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 16},
  [28] = {.lex_state = 16},
  [29] = {.lex_state = 16},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 16},
  [33] = {.lex_state = 16},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 16},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 5},
  [50] = {.lex_state = 16},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 16},
  [53] = {.lex_state = 16},
  [54] = {.lex_state = 16},
  [55] = {.lex_state = 16},
  [56] = {.lex_state = 16},
  [57] = {.lex_state = 16},
  [58] = {.lex_state = 16},
  [59] = {.lex_state = 16},
  [60] = {.lex_state = 16},
  [61] = {.lex_state = 16},
  [62] = {.lex_state = 16},
  [63] = {.lex_state = 16},
  [64] = {.lex_state = 16},
  [65] = {.lex_state = 16},
  [66] = {.lex_state = 16},
  [67] = {.lex_state = 16},
  [68] = {.lex_state = 16},
  [69] = {.lex_state = 16},
  [70] = {.lex_state = 16},
  [71] = {.lex_state = 16},
  [72] = {.lex_state = 16},
  [73] = {.lex_state = 16},
  [74] = {.lex_state = 16},
  [75] = {.lex_state = 16},
  [76] = {.lex_state = 16},
  [77] = {.lex_state = 16},
  [78] = {.lex_state = 16},
  [79] = {.lex_state = 16},
  [80] = {.lex_state = 16},
  [81] = {.lex_state = 16},
  [82] = {.lex_state = 16},
  [83] = {.lex_state = 16},
  [84] = {.lex_state = 16},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 16},
  [88] = {.lex_state = 16},
  [89] = {.lex_state = 16},
  [90] = {.lex_state = 16},
  [91] = {.lex_state = 6},
  [92] = {.lex_state = 6},
  [93] = {.lex_state = 6},
  [94] = {.lex_state = 16},
  [95] = {.lex_state = 16},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 16},
  [98] = {.lex_state = 16},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 6},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 6},
  [103] = {.lex_state = 4},
  [104] = {.lex_state = 15},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 4},
  [107] = {.lex_state = 15},
  [108] = {.lex_state = 16},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [aux_sym_identifier_token2] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [sym__digit] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym__hex_digit] = ACTIONS(1),
    [aux_sym__octal_token1] = ACTIONS(1),
    [aux_sym__octal_token2] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [anon_sym_1] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [sym__unicode_space] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym_single_line_comment_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(105),
    [sym_node] = STATE(45),
    [sym_identifier] = STATE(13),
    [sym__linespace] = STATE(88),
    [sym__ws] = STATE(88),
    [sym_single_line_comment] = STATE(88),
    [aux_sym_document_repeat1] = STATE(89),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_identifier_token1] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [anon_sym_] = ACTIONS(7),
    [sym__unicode_space] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 19,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      aux_sym_identifier_token1,
    ACTIONS(17), 1,
      sym__digit,
    ACTIONS(21), 1,
      anon_sym_0x,
    ACTIONS(23), 1,
      anon_sym_0o,
    ACTIONS(25), 1,
      anon_sym_0b,
    ACTIONS(29), 1,
      sym_null,
    STATE(30), 1,
      sym__integer,
    STATE(69), 1,
      sym__node_children,
    STATE(85), 1,
      sym__sign,
    STATE(108), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(19), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(27), 2,
      anon_sym_false,
      anon_sym_true,
    STATE(68), 2,
      sym__node_terminator,
      sym_single_line_comment,
    STATE(74), 2,
      sym_number,
      sym_boolean,
    STATE(73), 3,
      sym__node_prop_or_arg,
      sym_prop,
      sym_value,
    STATE(59), 4,
      sym__decimal,
      sym__hex,
      sym__octal,
      sym__binary,
  [68] = 19,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      aux_sym_identifier_token1,
    ACTIONS(17), 1,
      sym__digit,
    ACTIONS(21), 1,
      anon_sym_0x,
    ACTIONS(23), 1,
      anon_sym_0o,
    ACTIONS(25), 1,
      anon_sym_0b,
    ACTIONS(29), 1,
      sym_null,
    STATE(30), 1,
      sym__integer,
    STATE(69), 1,
      sym__node_children,
    STATE(85), 1,
      sym__sign,
    STATE(108), 1,
      sym_identifier,
    ACTIONS(19), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(27), 2,
      anon_sym_false,
      anon_sym_true,
    ACTIONS(31), 2,
      anon_sym_SEMI,
      sym__newline,
    STATE(67), 2,
      sym__node_terminator,
      sym_single_line_comment,
    STATE(74), 2,
      sym_number,
      sym_boolean,
    STATE(73), 3,
      sym__node_prop_or_arg,
      sym_prop,
      sym_value,
    STATE(59), 4,
      sym__decimal,
      sym__hex,
      sym__octal,
      sym__binary,
  [136] = 14,
    ACTIONS(15), 1,
      aux_sym_identifier_token1,
    ACTIONS(17), 1,
      sym__digit,
    ACTIONS(21), 1,
      anon_sym_0x,
    ACTIONS(23), 1,
      anon_sym_0o,
    ACTIONS(25), 1,
      anon_sym_0b,
    ACTIONS(29), 1,
      sym_null,
    STATE(30), 1,
      sym__integer,
    STATE(85), 1,
      sym__sign,
    STATE(108), 1,
      sym_identifier,
    ACTIONS(19), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(27), 2,
      anon_sym_false,
      anon_sym_true,
    STATE(74), 2,
      sym_number,
      sym_boolean,
    STATE(73), 3,
      sym__node_prop_or_arg,
      sym_prop,
      sym_value,
    STATE(59), 4,
      sym__decimal,
      sym__hex,
      sym__octal,
      sym__binary,
  [187] = 7,
    ACTIONS(39), 1,
      anon_sym_BSLASH,
    STATE(8), 1,
      sym__escline,
    STATE(12), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(35), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(37), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(6), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(33), 12,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [223] = 4,
    ACTIONS(43), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(45), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(6), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(41), 13,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [251] = 4,
    ACTIONS(37), 2,
      anon_sym_,
      sym__unicode_space,
    ACTIONS(50), 2,
      aux_sym_identifier_token1,
      sym__digit,
    STATE(6), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(48), 13,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [279] = 4,
    ACTIONS(54), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(56), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(7), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(52), 13,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [307] = 12,
    ACTIONS(17), 1,
      sym__digit,
    ACTIONS(21), 1,
      anon_sym_0x,
    ACTIONS(23), 1,
      anon_sym_0o,
    ACTIONS(25), 1,
      anon_sym_0b,
    ACTIONS(29), 1,
      sym_null,
    STATE(30), 1,
      sym__integer,
    STATE(77), 1,
      sym_value,
    STATE(85), 1,
      sym__sign,
    ACTIONS(19), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(27), 2,
      anon_sym_false,
      anon_sym_true,
    STATE(74), 2,
      sym_number,
      sym_boolean,
    STATE(59), 4,
      sym__decimal,
      sym__hex,
      sym__octal,
      sym__binary,
  [350] = 2,
    ACTIONS(60), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(58), 15,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [372] = 5,
    ACTIONS(62), 1,
      anon_sym_BSLASH,
    STATE(8), 1,
      sym__escline,
    STATE(11), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(50), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(48), 12,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [400] = 5,
    ACTIONS(39), 1,
      anon_sym_BSLASH,
    STATE(8), 1,
      sym__escline,
    STATE(11), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(67), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(65), 12,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [428] = 12,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(39), 1,
      anon_sym_BSLASH,
    STATE(3), 1,
      sym__node_space,
    STATE(8), 1,
      sym__escline,
    STATE(16), 1,
      aux_sym__node_space_repeat2,
    STATE(17), 1,
      aux_sym_node_repeat1,
    ACTIONS(69), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(71), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(5), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    STATE(18), 2,
      sym__node_children,
      aux_sym_node_repeat2,
    STATE(65), 2,
      sym__node_terminator,
      sym_single_line_comment,
  [470] = 2,
    ACTIONS(75), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(73), 15,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [492] = 2,
    ACTIONS(79), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(77), 15,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [514] = 5,
    ACTIONS(39), 1,
      anon_sym_BSLASH,
    STATE(8), 1,
      sym__escline,
    STATE(11), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(35), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(33), 12,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [542] = 12,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(39), 1,
      anon_sym_BSLASH,
    STATE(2), 1,
      sym__node_space,
    STATE(8), 1,
      sym__escline,
    STATE(16), 1,
      aux_sym__node_space_repeat2,
    STATE(21), 1,
      aux_sym_node_repeat1,
    ACTIONS(31), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(71), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(5), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    STATE(19), 2,
      sym__node_children,
      aux_sym_node_repeat2,
    STATE(67), 2,
      sym__node_terminator,
      sym_single_line_comment,
  [584] = 11,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(83), 1,
      anon_sym_BSLASH,
    STATE(50), 1,
      sym__escline,
    STATE(57), 1,
      sym__node_space,
    STATE(62), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(31), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(81), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(20), 2,
      sym__node_children,
      aux_sym_node_repeat2,
    STATE(28), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    STATE(67), 2,
      sym__node_terminator,
      sym_single_line_comment,
  [623] = 11,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(83), 1,
      anon_sym_BSLASH,
    STATE(50), 1,
      sym__escline,
    STATE(62), 1,
      aux_sym__node_space_repeat2,
    STATE(70), 1,
      sym__node_space,
    ACTIONS(13), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(81), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(20), 2,
      sym__node_children,
      aux_sym_node_repeat2,
    STATE(28), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    STATE(68), 2,
      sym__node_terminator,
      sym_single_line_comment,
  [662] = 9,
    ACTIONS(85), 1,
      anon_sym_LBRACE,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    STATE(50), 1,
      sym__escline,
    STATE(62), 1,
      aux_sym__node_space_repeat2,
    STATE(98), 1,
      sym__node_space,
    ACTIONS(90), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(20), 2,
      sym__node_children,
      aux_sym_node_repeat2,
    STATE(28), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(88), 3,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [695] = 8,
    ACTIONS(101), 1,
      anon_sym_BSLASH,
    STATE(4), 1,
      sym__node_space,
    STATE(8), 1,
      sym__escline,
    STATE(16), 1,
      aux_sym__node_space_repeat2,
    STATE(21), 1,
      aux_sym_node_repeat1,
    ACTIONS(98), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(5), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(96), 4,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [725] = 3,
    STATE(23), 1,
      aux_sym__integer_repeat1,
    ACTIONS(106), 2,
      anon_sym__,
      sym__digit,
    ACTIONS(104), 10,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_e,
      anon_sym_E,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [745] = 3,
    STATE(23), 1,
      aux_sym__integer_repeat1,
    ACTIONS(110), 2,
      anon_sym__,
      sym__digit,
    ACTIONS(108), 10,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_e,
      anon_sym_E,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [765] = 3,
    STATE(22), 1,
      aux_sym__integer_repeat1,
    ACTIONS(115), 2,
      anon_sym__,
      sym__digit,
    ACTIONS(113), 10,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_e,
      anon_sym_E,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [785] = 8,
    ACTIONS(5), 1,
      aux_sym_identifier_token1,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      sym_identifier,
    STATE(45), 1,
      sym_node,
    STATE(84), 1,
      aux_sym_document_repeat1,
    ACTIONS(119), 3,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
    STATE(87), 3,
      sym__linespace,
      sym__ws,
      sym_single_line_comment,
  [814] = 4,
    ACTIONS(123), 1,
      anon_sym_DOT,
    STATE(80), 1,
      sym__exponent,
    ACTIONS(125), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(121), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [834] = 3,
    STATE(27), 1,
      aux_sym__binary_repeat1,
    ACTIONS(129), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(127), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [852] = 6,
    ACTIONS(83), 1,
      anon_sym_BSLASH,
    STATE(50), 1,
      sym__escline,
    STATE(61), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(132), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(53), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(33), 4,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [876] = 3,
    STATE(27), 1,
      aux_sym__binary_repeat1,
    ACTIONS(136), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(134), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [894] = 4,
    ACTIONS(140), 1,
      anon_sym_DOT,
    STATE(63), 1,
      sym__exponent,
    ACTIONS(125), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(138), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [914] = 3,
    STATE(33), 1,
      aux_sym__binary_repeat1,
    ACTIONS(144), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(142), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [932] = 3,
    STATE(29), 1,
      aux_sym__binary_repeat1,
    ACTIONS(148), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(146), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [950] = 3,
    STATE(27), 1,
      aux_sym__binary_repeat1,
    ACTIONS(136), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(146), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [968] = 3,
    STATE(38), 1,
      aux_sym__hex_repeat1,
    ACTIONS(152), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(150), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [985] = 1,
    ACTIONS(73), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      aux_sym_identifier_token1,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [998] = 3,
    ACTIONS(156), 1,
      aux_sym_identifier_token2,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(154), 8,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1015] = 3,
    STATE(71), 1,
      sym__exponent,
    ACTIONS(125), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(159), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1032] = 3,
    STATE(38), 1,
      aux_sym__hex_repeat1,
    ACTIONS(163), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(161), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1049] = 3,
    STATE(41), 1,
      aux_sym__hex_repeat1,
    ACTIONS(166), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(150), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1066] = 3,
    STATE(34), 1,
      aux_sym__hex_repeat1,
    ACTIONS(170), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(168), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1083] = 3,
    STATE(38), 1,
      aux_sym__hex_repeat1,
    ACTIONS(152), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(172), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1100] = 3,
    ACTIONS(176), 1,
      aux_sym_identifier_token2,
    STATE(44), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(174), 8,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1117] = 3,
    STATE(64), 1,
      sym__exponent,
    ACTIONS(125), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(178), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1134] = 3,
    ACTIONS(182), 1,
      aux_sym_identifier_token2,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(180), 8,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1151] = 4,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(184), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
    ACTIONS(186), 3,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
    STATE(94), 3,
      sym__linespace,
      sym__ws,
      sym_single_line_comment,
  [1170] = 3,
    ACTIONS(190), 1,
      aux_sym__octal_token2,
    STATE(47), 1,
      aux_sym__octal_repeat1,
    ACTIONS(188), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1186] = 3,
    ACTIONS(194), 1,
      aux_sym__octal_token2,
    STATE(47), 1,
      aux_sym__octal_repeat1,
    ACTIONS(192), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1202] = 3,
    ACTIONS(199), 1,
      aux_sym__octal_token2,
    STATE(46), 1,
      aux_sym__octal_repeat1,
    ACTIONS(197), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1218] = 3,
    ACTIONS(190), 1,
      aux_sym__octal_token2,
    STATE(47), 1,
      aux_sym__octal_repeat1,
    ACTIONS(201), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1234] = 3,
    ACTIONS(203), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(52), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(52), 5,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1250] = 3,
    ACTIONS(205), 1,
      aux_sym__octal_token2,
    STATE(49), 1,
      aux_sym__octal_repeat1,
    ACTIONS(188), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1266] = 3,
    ACTIONS(132), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(53), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(48), 5,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1282] = 3,
    ACTIONS(207), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(53), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(41), 5,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1298] = 1,
    ACTIONS(210), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1308] = 5,
    ACTIONS(212), 1,
      sym__newline,
    ACTIONS(216), 1,
      anon_sym_SLASH_SLASH,
    STATE(10), 1,
      sym_single_line_comment,
    ACTIONS(214), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(81), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
  [1326] = 5,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(218), 1,
      sym__newline,
    STATE(15), 1,
      sym_single_line_comment,
    ACTIONS(132), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(53), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
  [1344] = 5,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    STATE(69), 1,
      sym__node_children,
    ACTIONS(13), 2,
      anon_sym_SEMI,
      sym__newline,
    STATE(68), 2,
      sym__node_terminator,
      sym_single_line_comment,
  [1362] = 5,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(212), 1,
      sym__newline,
    STATE(10), 1,
      sym_single_line_comment,
    ACTIONS(220), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(56), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
  [1380] = 1,
    ACTIONS(222), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1390] = 4,
    ACTIONS(224), 1,
      anon_sym_BSLASH,
    STATE(50), 1,
      sym__escline,
    STATE(60), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(48), 4,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [1406] = 4,
    ACTIONS(83), 1,
      anon_sym_BSLASH,
    STATE(50), 1,
      sym__escline,
    STATE(60), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(65), 4,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [1422] = 4,
    ACTIONS(83), 1,
      anon_sym_BSLASH,
    STATE(50), 1,
      sym__escline,
    STATE(60), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(33), 4,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [1438] = 1,
    ACTIONS(121), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1448] = 1,
    ACTIONS(227), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1458] = 1,
    ACTIONS(229), 7,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_SLASH_SLASH,
  [1468] = 1,
    ACTIONS(231), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1478] = 1,
    ACTIONS(233), 7,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_SLASH_SLASH,
  [1488] = 1,
    ACTIONS(235), 7,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_SLASH_SLASH,
  [1498] = 1,
    ACTIONS(88), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1508] = 5,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    STATE(69), 1,
      sym__node_children,
    ACTIONS(237), 2,
      anon_sym_SEMI,
      sym__newline,
    STATE(78), 2,
      sym__node_terminator,
      sym_single_line_comment,
  [1526] = 1,
    ACTIONS(178), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1536] = 1,
    ACTIONS(239), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1546] = 1,
    ACTIONS(96), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1556] = 1,
    ACTIONS(241), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1566] = 1,
    ACTIONS(243), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1576] = 1,
    ACTIONS(245), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1586] = 1,
    ACTIONS(247), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1596] = 1,
    ACTIONS(249), 7,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_SLASH_SLASH,
  [1606] = 1,
    ACTIONS(251), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1616] = 1,
    ACTIONS(159), 7,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1626] = 5,
    ACTIONS(216), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(218), 1,
      sym__newline,
    STATE(15), 1,
      sym_single_line_comment,
    ACTIONS(132), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(53), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
  [1644] = 5,
    ACTIONS(255), 1,
      aux_sym_identifier_token1,
    STATE(13), 1,
      sym_identifier,
    STATE(45), 1,
      sym_node,
    STATE(82), 1,
      aux_sym_document_repeat1,
    ACTIONS(253), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1661] = 5,
    ACTIONS(5), 1,
      aux_sym_identifier_token1,
    ACTIONS(258), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      sym_identifier,
    STATE(45), 1,
      sym_node,
    STATE(82), 1,
      aux_sym_document_repeat1,
  [1677] = 5,
    ACTIONS(5), 1,
      aux_sym_identifier_token1,
    ACTIONS(260), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      sym_identifier,
    STATE(45), 1,
      sym_node,
    STATE(82), 1,
      aux_sym_document_repeat1,
  [1693] = 5,
    ACTIONS(17), 1,
      sym__digit,
    ACTIONS(262), 1,
      anon_sym_0x,
    ACTIONS(264), 1,
      anon_sym_0o,
    ACTIONS(266), 1,
      anon_sym_0b,
    STATE(26), 1,
      sym__integer,
  [1709] = 4,
    ACTIONS(268), 1,
      sym__digit,
    STATE(79), 1,
      sym__integer,
    STATE(101), 1,
      sym__sign,
    ACTIONS(270), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1723] = 5,
    ACTIONS(5), 1,
      aux_sym_identifier_token1,
    ACTIONS(260), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      sym_identifier,
    STATE(45), 1,
      sym_node,
    STATE(83), 1,
      aux_sym_document_repeat1,
  [1739] = 5,
    ACTIONS(5), 1,
      aux_sym_identifier_token1,
    ACTIONS(272), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_identifier,
    STATE(45), 1,
      sym_node,
    STATE(90), 1,
      aux_sym_document_repeat1,
  [1755] = 5,
    ACTIONS(5), 1,
      aux_sym_identifier_token1,
    ACTIONS(272), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_identifier,
    STATE(45), 1,
      sym_node,
    STATE(82), 1,
      aux_sym_document_repeat1,
  [1771] = 5,
    ACTIONS(5), 1,
      aux_sym_identifier_token1,
    ACTIONS(274), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_identifier,
    STATE(45), 1,
      sym_node,
    STATE(82), 1,
      aux_sym_document_repeat1,
  [1787] = 3,
    ACTIONS(276), 1,
      sym__newline,
    ACTIONS(278), 1,
      aux_sym_single_line_comment_token1,
    STATE(92), 1,
      aux_sym_single_line_comment_repeat1,
  [1797] = 3,
    ACTIONS(280), 1,
      sym__newline,
    ACTIONS(282), 1,
      aux_sym_single_line_comment_token1,
    STATE(92), 1,
      aux_sym_single_line_comment_repeat1,
  [1807] = 3,
    ACTIONS(278), 1,
      aux_sym_single_line_comment_token1,
    ACTIONS(285), 1,
      sym__newline,
    STATE(92), 1,
      aux_sym_single_line_comment_repeat1,
  [1817] = 1,
    ACTIONS(253), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
  [1823] = 1,
    ACTIONS(287), 2,
      anon_sym_0,
      anon_sym_1,
  [1828] = 2,
    ACTIONS(268), 1,
      sym__digit,
    STATE(43), 1,
      sym__integer,
  [1835] = 1,
    ACTIONS(289), 2,
      anon_sym_0,
      anon_sym_1,
  [1840] = 2,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    STATE(69), 1,
      sym__node_children,
  [1847] = 2,
    ACTIONS(268), 1,
      sym__digit,
    STATE(37), 1,
      sym__integer,
  [1854] = 2,
    ACTIONS(291), 1,
      aux_sym_single_line_comment_token1,
    STATE(91), 1,
      aux_sym_single_line_comment_repeat1,
  [1861] = 2,
    ACTIONS(268), 1,
      sym__digit,
    STATE(66), 1,
      sym__integer,
  [1868] = 2,
    ACTIONS(293), 1,
      aux_sym_single_line_comment_token1,
    STATE(93), 1,
      aux_sym_single_line_comment_repeat1,
  [1875] = 1,
    ACTIONS(295), 1,
      sym__hex_digit,
  [1879] = 1,
    ACTIONS(297), 1,
      aux_sym__octal_token1,
  [1883] = 1,
    ACTIONS(299), 1,
      ts_builtin_sym_end,
  [1887] = 1,
    ACTIONS(301), 1,
      sym__hex_digit,
  [1891] = 1,
    ACTIONS(303), 1,
      aux_sym__octal_token1,
  [1895] = 1,
    ACTIONS(305), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 68,
  [SMALL_STATE(4)] = 136,
  [SMALL_STATE(5)] = 187,
  [SMALL_STATE(6)] = 223,
  [SMALL_STATE(7)] = 251,
  [SMALL_STATE(8)] = 279,
  [SMALL_STATE(9)] = 307,
  [SMALL_STATE(10)] = 350,
  [SMALL_STATE(11)] = 372,
  [SMALL_STATE(12)] = 400,
  [SMALL_STATE(13)] = 428,
  [SMALL_STATE(14)] = 470,
  [SMALL_STATE(15)] = 492,
  [SMALL_STATE(16)] = 514,
  [SMALL_STATE(17)] = 542,
  [SMALL_STATE(18)] = 584,
  [SMALL_STATE(19)] = 623,
  [SMALL_STATE(20)] = 662,
  [SMALL_STATE(21)] = 695,
  [SMALL_STATE(22)] = 725,
  [SMALL_STATE(23)] = 745,
  [SMALL_STATE(24)] = 765,
  [SMALL_STATE(25)] = 785,
  [SMALL_STATE(26)] = 814,
  [SMALL_STATE(27)] = 834,
  [SMALL_STATE(28)] = 852,
  [SMALL_STATE(29)] = 876,
  [SMALL_STATE(30)] = 894,
  [SMALL_STATE(31)] = 914,
  [SMALL_STATE(32)] = 932,
  [SMALL_STATE(33)] = 950,
  [SMALL_STATE(34)] = 968,
  [SMALL_STATE(35)] = 985,
  [SMALL_STATE(36)] = 998,
  [SMALL_STATE(37)] = 1015,
  [SMALL_STATE(38)] = 1032,
  [SMALL_STATE(39)] = 1049,
  [SMALL_STATE(40)] = 1066,
  [SMALL_STATE(41)] = 1083,
  [SMALL_STATE(42)] = 1100,
  [SMALL_STATE(43)] = 1117,
  [SMALL_STATE(44)] = 1134,
  [SMALL_STATE(45)] = 1151,
  [SMALL_STATE(46)] = 1170,
  [SMALL_STATE(47)] = 1186,
  [SMALL_STATE(48)] = 1202,
  [SMALL_STATE(49)] = 1218,
  [SMALL_STATE(50)] = 1234,
  [SMALL_STATE(51)] = 1250,
  [SMALL_STATE(52)] = 1266,
  [SMALL_STATE(53)] = 1282,
  [SMALL_STATE(54)] = 1298,
  [SMALL_STATE(55)] = 1308,
  [SMALL_STATE(56)] = 1326,
  [SMALL_STATE(57)] = 1344,
  [SMALL_STATE(58)] = 1362,
  [SMALL_STATE(59)] = 1380,
  [SMALL_STATE(60)] = 1390,
  [SMALL_STATE(61)] = 1406,
  [SMALL_STATE(62)] = 1422,
  [SMALL_STATE(63)] = 1438,
  [SMALL_STATE(64)] = 1448,
  [SMALL_STATE(65)] = 1458,
  [SMALL_STATE(66)] = 1468,
  [SMALL_STATE(67)] = 1478,
  [SMALL_STATE(68)] = 1488,
  [SMALL_STATE(69)] = 1498,
  [SMALL_STATE(70)] = 1508,
  [SMALL_STATE(71)] = 1526,
  [SMALL_STATE(72)] = 1536,
  [SMALL_STATE(73)] = 1546,
  [SMALL_STATE(74)] = 1556,
  [SMALL_STATE(75)] = 1566,
  [SMALL_STATE(76)] = 1576,
  [SMALL_STATE(77)] = 1586,
  [SMALL_STATE(78)] = 1596,
  [SMALL_STATE(79)] = 1606,
  [SMALL_STATE(80)] = 1616,
  [SMALL_STATE(81)] = 1626,
  [SMALL_STATE(82)] = 1644,
  [SMALL_STATE(83)] = 1661,
  [SMALL_STATE(84)] = 1677,
  [SMALL_STATE(85)] = 1693,
  [SMALL_STATE(86)] = 1709,
  [SMALL_STATE(87)] = 1723,
  [SMALL_STATE(88)] = 1739,
  [SMALL_STATE(89)] = 1755,
  [SMALL_STATE(90)] = 1771,
  [SMALL_STATE(91)] = 1787,
  [SMALL_STATE(92)] = 1797,
  [SMALL_STATE(93)] = 1807,
  [SMALL_STATE(94)] = 1817,
  [SMALL_STATE(95)] = 1823,
  [SMALL_STATE(96)] = 1828,
  [SMALL_STATE(97)] = 1835,
  [SMALL_STATE(98)] = 1840,
  [SMALL_STATE(99)] = 1847,
  [SMALL_STATE(100)] = 1854,
  [SMALL_STATE(101)] = 1861,
  [SMALL_STATE(102)] = 1868,
  [SMALL_STATE(103)] = 1875,
  [SMALL_STATE(104)] = 1879,
  [SMALL_STATE(105)] = 1883,
  [SMALL_STATE(106)] = 1887,
  [SMALL_STATE(107)] = 1891,
  [SMALL_STATE(108)] = 1895,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_space, 1),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__node_space, 1),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__node_space_repeat1, 2),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__node_space_repeat1, 2),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__node_space_repeat1, 2), SHIFT_REPEAT(6),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__node_space_repeat2, 2),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__node_space_repeat2, 2),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__node_space_repeat2, 1),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__node_space_repeat2, 1),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__escline, 2),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__escline, 2),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__node_space_repeat2, 2), SHIFT_REPEAT(55),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_space, 2),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__node_space, 2),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_line_comment, 3),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_single_line_comment, 3),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__escline, 3),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__escline, 3),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_repeat2, 2), SHIFT_REPEAT(25),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_node_repeat2, 2),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_repeat2, 2), SHIFT_REPEAT(28),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_repeat2, 2), SHIFT_REPEAT(58),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_node_repeat1, 2),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_repeat1, 2), SHIFT_REPEAT(5),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_repeat1, 2), SHIFT_REPEAT(55),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__integer, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__integer_repeat1, 2),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__integer_repeat1, 2), SHIFT_REPEAT(23),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__integer, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 2),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__binary_repeat1, 2),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__binary_repeat1, 2), SHIFT_REPEAT(27),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binary, 4),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binary, 2),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binary, 3),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex, 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifier_repeat1, 2),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifier_repeat1, 2), SHIFT_REPEAT(36),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 3),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__hex_repeat1, 2),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__hex_repeat1, 2), SHIFT_REPEAT(38),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex, 2),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex, 4),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 4),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__octal, 3),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__octal_repeat1, 2),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__octal_repeat1, 2), SHIFT_REPEAT(47),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__octal, 2),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__octal, 4),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__node_space_repeat1, 2), SHIFT_REPEAT(53),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_children, 3),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__node_space_repeat2, 2), SHIFT_REPEAT(58),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 5),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 2),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exponent, 3),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 3),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 4),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_children, 4),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_children, 2),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prop, 3),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 5),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exponent, 2),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [255] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(42),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_single_line_comment_repeat1, 2),
  [282] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_single_line_comment_repeat1, 2), SHIFT_REPEAT(92),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [299] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_kdl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
