#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 85
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_SEMI = 1,
  anon_sym_EQ = 2,
  aux_sym_identifier_token1 = 3,
  anon_sym_DOT = 4,
  anon_sym_e = 5,
  anon_sym_E = 6,
  anon_sym__ = 7,
  sym__digit = 8,
  anon_sym_PLUS = 9,
  anon_sym_DASH = 10,
  anon_sym_0x = 11,
  sym__hex_digit = 12,
  anon_sym_0o = 13,
  aux_sym__octal_token1 = 14,
  aux_sym__octal_token2 = 15,
  anon_sym_0b = 16,
  anon_sym_0 = 17,
  anon_sym_1 = 18,
  anon_sym_false = 19,
  anon_sym_true = 20,
  sym_null = 21,
  sym__newline = 22,
  anon_sym_ = 23,
  sym__unicode_space = 24,
  anon_sym_BSLASH = 25,
  anon_sym_SLASH_SLASH = 26,
  aux_sym__single_line_comment_token1 = 27,
  sym_document = 28,
  sym_node = 29,
  sym__node_prop_or_arg = 30,
  sym__node_space = 31,
  sym__node_terminator = 32,
  sym_prop = 33,
  sym_identifier = 34,
  sym_value = 35,
  sym_number = 36,
  sym__decimal = 37,
  sym__exponent = 38,
  sym__integer = 39,
  sym__sign = 40,
  sym__hex = 41,
  sym__octal = 42,
  sym__binary = 43,
  sym_boolean = 44,
  sym__linespace = 45,
  sym__ws = 46,
  sym__escline = 47,
  sym__single_line_comment = 48,
  aux_sym_document_repeat1 = 49,
  aux_sym_node_repeat1 = 50,
  aux_sym__node_space_repeat1 = 51,
  aux_sym__node_space_repeat2 = 52,
  aux_sym_identifier_repeat1 = 53,
  aux_sym__integer_repeat1 = 54,
  aux_sym__hex_repeat1 = 55,
  aux_sym__octal_repeat1 = 56,
  aux_sym__binary_repeat1 = 57,
  aux_sym__single_line_comment_repeat1 = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [aux_sym_identifier_token1] = "identifier_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_e] = "e",
  [anon_sym_E] = "E",
  [anon_sym__] = "_",
  [sym__digit] = "_digit",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_0x] = "0x",
  [sym__hex_digit] = "_hex_digit",
  [anon_sym_0o] = "0o",
  [aux_sym__octal_token1] = "_octal_token1",
  [aux_sym__octal_token2] = "_octal_token2",
  [anon_sym_0b] = "0b",
  [anon_sym_0] = "0",
  [anon_sym_1] = "1",
  [anon_sym_false] = "false",
  [anon_sym_true] = "true",
  [sym_null] = "null",
  [sym__newline] = "_newline",
  [anon_sym_] = "﻿",
  [sym__unicode_space] = "_unicode_space",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym__single_line_comment_token1] = "_single_line_comment_token1",
  [sym_document] = "document",
  [sym_node] = "node",
  [sym__node_prop_or_arg] = "_node_prop_or_arg",
  [sym__node_space] = "_node_space",
  [sym__node_terminator] = "_node_terminator",
  [sym_prop] = "prop",
  [sym_identifier] = "identifier",
  [sym_value] = "value",
  [sym_number] = "number",
  [sym__decimal] = "_decimal",
  [sym__exponent] = "_exponent",
  [sym__integer] = "_integer",
  [sym__sign] = "_sign",
  [sym__hex] = "_hex",
  [sym__octal] = "_octal",
  [sym__binary] = "_binary",
  [sym_boolean] = "boolean",
  [sym__linespace] = "_linespace",
  [sym__ws] = "_ws",
  [sym__escline] = "_escline",
  [sym__single_line_comment] = "_single_line_comment",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_node_repeat1] = "node_repeat1",
  [aux_sym__node_space_repeat1] = "_node_space_repeat1",
  [aux_sym__node_space_repeat2] = "_node_space_repeat2",
  [aux_sym_identifier_repeat1] = "identifier_repeat1",
  [aux_sym__integer_repeat1] = "_integer_repeat1",
  [aux_sym__hex_repeat1] = "_hex_repeat1",
  [aux_sym__octal_repeat1] = "_octal_repeat1",
  [aux_sym__binary_repeat1] = "_binary_repeat1",
  [aux_sym__single_line_comment_repeat1] = "_single_line_comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_E] = anon_sym_E,
  [anon_sym__] = anon_sym__,
  [sym__digit] = sym__digit,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_0x] = anon_sym_0x,
  [sym__hex_digit] = sym__hex_digit,
  [anon_sym_0o] = anon_sym_0o,
  [aux_sym__octal_token1] = aux_sym__octal_token1,
  [aux_sym__octal_token2] = aux_sym__octal_token2,
  [anon_sym_0b] = anon_sym_0b,
  [anon_sym_0] = anon_sym_0,
  [anon_sym_1] = anon_sym_1,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_true] = anon_sym_true,
  [sym_null] = sym_null,
  [sym__newline] = sym__newline,
  [anon_sym_] = anon_sym_,
  [sym__unicode_space] = sym__unicode_space,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym__single_line_comment_token1] = aux_sym__single_line_comment_token1,
  [sym_document] = sym_document,
  [sym_node] = sym_node,
  [sym__node_prop_or_arg] = sym__node_prop_or_arg,
  [sym__node_space] = sym__node_space,
  [sym__node_terminator] = sym__node_terminator,
  [sym_prop] = sym_prop,
  [sym_identifier] = sym_identifier,
  [sym_value] = sym_value,
  [sym_number] = sym_number,
  [sym__decimal] = sym__decimal,
  [sym__exponent] = sym__exponent,
  [sym__integer] = sym__integer,
  [sym__sign] = sym__sign,
  [sym__hex] = sym__hex,
  [sym__octal] = sym__octal,
  [sym__binary] = sym__binary,
  [sym_boolean] = sym_boolean,
  [sym__linespace] = sym__linespace,
  [sym__ws] = sym__ws,
  [sym__escline] = sym__escline,
  [sym__single_line_comment] = sym__single_line_comment,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_node_repeat1] = aux_sym_node_repeat1,
  [aux_sym__node_space_repeat1] = aux_sym__node_space_repeat1,
  [aux_sym__node_space_repeat2] = aux_sym__node_space_repeat2,
  [aux_sym_identifier_repeat1] = aux_sym_identifier_repeat1,
  [aux_sym__integer_repeat1] = aux_sym__integer_repeat1,
  [aux_sym__hex_repeat1] = aux_sym__hex_repeat1,
  [aux_sym__octal_repeat1] = aux_sym__octal_repeat1,
  [aux_sym__binary_repeat1] = aux_sym__binary_repeat1,
  [aux_sym__single_line_comment_repeat1] = aux_sym__single_line_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [sym__digit] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0x] = {
    .visible = true,
    .named = false,
  },
  [sym__hex_digit] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_0o] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__octal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__octal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_0b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [sym__unicode_space] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__single_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_node] = {
    .visible = true,
    .named = true,
  },
  [sym__node_prop_or_arg] = {
    .visible = false,
    .named = true,
  },
  [sym__node_space] = {
    .visible = false,
    .named = true,
  },
  [sym__node_terminator] = {
    .visible = false,
    .named = true,
  },
  [sym_prop] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym__decimal] = {
    .visible = false,
    .named = true,
  },
  [sym__exponent] = {
    .visible = false,
    .named = true,
  },
  [sym__integer] = {
    .visible = false,
    .named = true,
  },
  [sym__sign] = {
    .visible = false,
    .named = true,
  },
  [sym__hex] = {
    .visible = false,
    .named = true,
  },
  [sym__octal] = {
    .visible = false,
    .named = true,
  },
  [sym__binary] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym__linespace] = {
    .visible = false,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [sym__escline] = {
    .visible = false,
    .named = true,
  },
  [sym__single_line_comment] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_node_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__node_space_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__node_space_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__integer_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__hex_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__octal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__binary_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__single_line_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == ' ') ADVANCE(44);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '0') ADVANCE(37);
      if (lookahead == '1') ADVANCE(38);
      if (lookahead == ';') ADVANCE(17);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == 'E') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == '_') ADVANCE(26);
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead == 65279) ADVANCE(43);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'F')) ADVANCE(32);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      if (('2' <= lookahead && lookahead <= '7')) ADVANCE(27);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == ' ') ADVANCE(44);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(28);
      if (lookahead == ';') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == 'f') ADVANCE(20);
      if (lookahead == 'n') ADVANCE(22);
      if (lookahead == 't') ADVANCE(21);
      if (lookahead == 65279) ADVANCE(43);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == ' ') ADVANCE(44);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ';') ADVANCE(17);
      if (lookahead == 'E') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == '_') ADVANCE(26);
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead == 65279) ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == ' ') ADVANCE(44);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ';') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == '_') ADVANCE(26);
      if (lookahead == 65279) ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == ' ') ADVANCE(44);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ';') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == 65279) ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(35);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(46);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(34);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == ' ') ADVANCE(44);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(37);
      if (lookahead == '1') ADVANCE(38);
      if (lookahead == ';') ADVANCE(17);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == '_') ADVANCE(26);
      if (lookahead == 65279) ADVANCE(43);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_E);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__digit);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__digit);
      if (lookahead == 'b') ADVANCE(36);
      if (lookahead == 'o') ADVANCE(33);
      if (lookahead == 'x') ADVANCE(31);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_0x);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__hex_digit);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_0o);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym__octal_token1);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym__octal_token2);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_0b);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_1);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__unicode_space);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym__single_line_comment_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 15},
  [17] = {.lex_state = 15},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 15},
  [22] = {.lex_state = 15},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 15},
  [26] = {.lex_state = 15},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 15},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 15},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 15},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 15},
  [45] = {.lex_state = 15},
  [46] = {.lex_state = 15},
  [47] = {.lex_state = 15},
  [48] = {.lex_state = 15},
  [49] = {.lex_state = 15},
  [50] = {.lex_state = 15},
  [51] = {.lex_state = 15},
  [52] = {.lex_state = 15},
  [53] = {.lex_state = 15},
  [54] = {.lex_state = 15},
  [55] = {.lex_state = 15},
  [56] = {.lex_state = 15},
  [57] = {.lex_state = 15},
  [58] = {.lex_state = 15},
  [59] = {.lex_state = 15},
  [60] = {.lex_state = 15},
  [61] = {.lex_state = 15},
  [62] = {.lex_state = 15},
  [63] = {.lex_state = 15},
  [64] = {.lex_state = 15},
  [65] = {.lex_state = 15},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 5},
  [69] = {.lex_state = 5},
  [70] = {.lex_state = 5},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 15},
  [74] = {.lex_state = 15},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 15},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 5},
  [79] = {.lex_state = 14},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 15},
  [82] = {.lex_state = 14},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [sym__digit] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym__hex_digit] = ACTIONS(1),
    [aux_sym__octal_token1] = ACTIONS(1),
    [aux_sym__octal_token2] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [anon_sym_1] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [sym__unicode_space] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym__single_line_comment_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(84),
    [sym_node] = STATE(38),
    [sym_identifier] = STATE(17),
    [sym__linespace] = STATE(50),
    [sym__ws] = STATE(50),
    [sym__single_line_comment] = STATE(50),
    [aux_sym_document_repeat1] = STATE(52),
    [aux_sym_identifier_repeat1] = STATE(36),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_identifier_token1] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [anon_sym_] = ACTIONS(7),
    [sym__unicode_space] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(13), 1,
      aux_sym_identifier_token1,
    ACTIONS(15), 1,
      sym__digit,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_0o,
    ACTIONS(23), 1,
      anon_sym_0b,
    ACTIONS(27), 1,
      sym_null,
    STATE(24), 1,
      sym__integer,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    STATE(67), 1,
      sym__sign,
    STATE(81), 1,
      sym_identifier,
    ACTIONS(11), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_false,
      anon_sym_true,
    STATE(58), 2,
      sym__node_terminator,
      sym__single_line_comment,
    STATE(60), 2,
      sym_number,
      sym_boolean,
    STATE(59), 3,
      sym__node_prop_or_arg,
      sym_prop,
      sym_value,
    STATE(55), 4,
      sym__decimal,
      sym__hex,
      sym__octal,
      sym__binary,
  [65] = 18,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(13), 1,
      aux_sym_identifier_token1,
    ACTIONS(15), 1,
      sym__digit,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_0o,
    ACTIONS(23), 1,
      anon_sym_0b,
    ACTIONS(27), 1,
      sym_null,
    STATE(24), 1,
      sym__integer,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    STATE(67), 1,
      sym__sign,
    STATE(81), 1,
      sym_identifier,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_false,
      anon_sym_true,
    ACTIONS(29), 2,
      anon_sym_SEMI,
      sym__newline,
    STATE(56), 2,
      sym__node_terminator,
      sym__single_line_comment,
    STATE(60), 2,
      sym_number,
      sym_boolean,
    STATE(59), 3,
      sym__node_prop_or_arg,
      sym_prop,
      sym_value,
    STATE(55), 4,
      sym__decimal,
      sym__hex,
      sym__octal,
      sym__binary,
  [130] = 15,
    ACTIONS(13), 1,
      aux_sym_identifier_token1,
    ACTIONS(15), 1,
      sym__digit,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_0o,
    ACTIONS(23), 1,
      anon_sym_0b,
    ACTIONS(27), 1,
      sym_null,
    STATE(24), 1,
      sym__integer,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    STATE(67), 1,
      sym__sign,
    STATE(81), 1,
      sym_identifier,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_false,
      anon_sym_true,
    STATE(60), 2,
      sym_number,
      sym_boolean,
    STATE(59), 3,
      sym__node_prop_or_arg,
      sym_prop,
      sym_value,
    STATE(55), 4,
      sym__decimal,
      sym__hex,
      sym__octal,
      sym__binary,
  [184] = 7,
    ACTIONS(37), 1,
      anon_sym_BSLASH,
    STATE(7), 1,
      sym__escline,
    STATE(15), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(33), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(35), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(9), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(31), 11,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [219] = 4,
    ACTIONS(35), 2,
      anon_sym_,
      sym__unicode_space,
    ACTIONS(41), 2,
      aux_sym_identifier_token1,
      sym__digit,
    STATE(9), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(39), 12,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [246] = 4,
    ACTIONS(45), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(47), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(6), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(43), 12,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [273] = 12,
    ACTIONS(15), 1,
      sym__digit,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_0o,
    ACTIONS(23), 1,
      anon_sym_0b,
    ACTIONS(27), 1,
      sym_null,
    STATE(24), 1,
      sym__integer,
    STATE(62), 1,
      sym_value,
    STATE(67), 1,
      sym__sign,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_false,
      anon_sym_true,
    STATE(60), 2,
      sym_number,
      sym_boolean,
    STATE(55), 4,
      sym__decimal,
      sym__hex,
      sym__octal,
      sym__binary,
  [316] = 4,
    ACTIONS(51), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(53), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(9), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(49), 12,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [343] = 5,
    ACTIONS(56), 1,
      anon_sym_BSLASH,
    STATE(7), 1,
      sym__escline,
    STATE(10), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(41), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(39), 11,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [370] = 2,
    ACTIONS(61), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(59), 14,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [391] = 2,
    ACTIONS(65), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(63), 14,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [412] = 5,
    ACTIONS(37), 1,
      anon_sym_BSLASH,
    STATE(7), 1,
      sym__escline,
    STATE(10), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(33), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(31), 11,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [439] = 2,
    ACTIONS(69), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(67), 14,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [460] = 5,
    ACTIONS(37), 1,
      anon_sym_BSLASH,
    STATE(7), 1,
      sym__escline,
    STATE(10), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(73), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(71), 11,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [487] = 10,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(37), 1,
      anon_sym_BSLASH,
    STATE(3), 1,
      sym__node_space,
    STATE(7), 1,
      sym__escline,
    STATE(13), 1,
      aux_sym__node_space_repeat2,
    STATE(21), 1,
      aux_sym_node_repeat1,
    ACTIONS(11), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(75), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(5), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    STATE(58), 2,
      sym__node_terminator,
      sym__single_line_comment,
  [522] = 10,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(37), 1,
      anon_sym_BSLASH,
    STATE(2), 1,
      sym__node_space,
    STATE(7), 1,
      sym__escline,
    STATE(13), 1,
      aux_sym__node_space_repeat2,
    STATE(16), 1,
      aux_sym_node_repeat1,
    ACTIONS(75), 2,
      anon_sym_,
      sym__unicode_space,
    ACTIONS(77), 2,
      anon_sym_SEMI,
      sym__newline,
    STATE(5), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    STATE(54), 2,
      sym__node_terminator,
      sym__single_line_comment,
  [557] = 3,
    STATE(20), 1,
      aux_sym__integer_repeat1,
    ACTIONS(81), 2,
      anon_sym__,
      sym__digit,
    ACTIONS(79), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_e,
      anon_sym_E,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [576] = 3,
    STATE(18), 1,
      aux_sym__integer_repeat1,
    ACTIONS(85), 2,
      anon_sym__,
      sym__digit,
    ACTIONS(83), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_e,
      anon_sym_E,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [595] = 3,
    STATE(20), 1,
      aux_sym__integer_repeat1,
    ACTIONS(89), 2,
      anon_sym__,
      sym__digit,
    ACTIONS(87), 9,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_e,
      anon_sym_E,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [614] = 8,
    ACTIONS(97), 1,
      anon_sym_BSLASH,
    STATE(4), 1,
      sym__node_space,
    STATE(7), 1,
      sym__escline,
    STATE(13), 1,
      aux_sym__node_space_repeat2,
    STATE(21), 1,
      aux_sym_node_repeat1,
    ACTIONS(94), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(5), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(92), 3,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_SLASH_SLASH,
  [643] = 3,
    STATE(22), 1,
      aux_sym__binary_repeat1,
    ACTIONS(102), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(100), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [660] = 4,
    ACTIONS(107), 1,
      anon_sym_DOT,
    STATE(65), 1,
      sym__exponent,
    ACTIONS(109), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(105), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [679] = 4,
    ACTIONS(113), 1,
      anon_sym_DOT,
    STATE(51), 1,
      sym__exponent,
    ACTIONS(109), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(111), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [698] = 3,
    STATE(27), 1,
      aux_sym__binary_repeat1,
    ACTIONS(117), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(115), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [715] = 3,
    STATE(28), 1,
      aux_sym__binary_repeat1,
    ACTIONS(121), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(119), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [732] = 3,
    STATE(22), 1,
      aux_sym__binary_repeat1,
    ACTIONS(125), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(123), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [749] = 3,
    STATE(22), 1,
      aux_sym__binary_repeat1,
    ACTIONS(125), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(115), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [766] = 3,
    STATE(29), 1,
      aux_sym__hex_repeat1,
    ACTIONS(129), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(127), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [782] = 3,
    STATE(47), 1,
      sym__exponent,
    ACTIONS(109), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(132), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [798] = 3,
    STATE(35), 1,
      aux_sym__hex_repeat1,
    ACTIONS(136), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(134), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [814] = 3,
    STATE(29), 1,
      aux_sym__hex_repeat1,
    ACTIONS(138), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(134), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [830] = 3,
    STATE(49), 1,
      sym__exponent,
    ACTIONS(109), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(140), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [846] = 3,
    ACTIONS(144), 1,
      aux_sym_identifier_token1,
    STATE(34), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(142), 7,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [862] = 3,
    STATE(29), 1,
      aux_sym__hex_repeat1,
    ACTIONS(138), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(147), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [878] = 3,
    ACTIONS(151), 1,
      aux_sym_identifier_token1,
    STATE(34), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(149), 7,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [894] = 3,
    STATE(32), 1,
      aux_sym__hex_repeat1,
    ACTIONS(155), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(153), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [910] = 4,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      aux_sym_identifier_token1,
    ACTIONS(159), 3,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
    STATE(76), 3,
      sym__linespace,
      sym__ws,
      sym__single_line_comment,
  [928] = 3,
    ACTIONS(163), 1,
      aux_sym__octal_token2,
    STATE(41), 1,
      aux_sym__octal_repeat1,
    ACTIONS(161), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [943] = 3,
    ACTIONS(165), 1,
      aux_sym__octal_token2,
    STATE(43), 1,
      aux_sym__octal_repeat1,
    ACTIONS(161), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [958] = 3,
    ACTIONS(165), 1,
      aux_sym__octal_token2,
    STATE(43), 1,
      aux_sym__octal_repeat1,
    ACTIONS(167), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [973] = 3,
    ACTIONS(171), 1,
      aux_sym__octal_token2,
    STATE(40), 1,
      aux_sym__octal_repeat1,
    ACTIONS(169), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [988] = 3,
    ACTIONS(175), 1,
      aux_sym__octal_token2,
    STATE(43), 1,
      aux_sym__octal_repeat1,
    ACTIONS(173), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1003] = 5,
    ACTIONS(178), 1,
      sym__newline,
    ACTIONS(182), 1,
      anon_sym_SLASH_SLASH,
    STATE(11), 1,
      sym__single_line_comment,
    ACTIONS(180), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(48), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
  [1021] = 5,
    ACTIONS(182), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(184), 1,
      sym__newline,
    STATE(14), 1,
      sym__single_line_comment,
    ACTIONS(186), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(44), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
  [1039] = 1,
    ACTIONS(63), 6,
      ts_builtin_sym_end,
      aux_sym_identifier_token1,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_SLASH_SLASH,
  [1048] = 1,
    ACTIONS(140), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1057] = 3,
    ACTIONS(49), 2,
      sym__newline,
      anon_sym_SLASH_SLASH,
    ACTIONS(188), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(48), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
  [1070] = 1,
    ACTIONS(191), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1079] = 6,
    ACTIONS(5), 1,
      aux_sym_identifier_token1,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      sym_identifier,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    STATE(38), 1,
      sym_node,
    STATE(57), 1,
      aux_sym_document_repeat1,
  [1098] = 1,
    ACTIONS(105), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1107] = 6,
    ACTIONS(5), 1,
      aux_sym_identifier_token1,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      sym_identifier,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    STATE(38), 1,
      sym_node,
    STATE(63), 1,
      aux_sym_document_repeat1,
  [1126] = 1,
    ACTIONS(195), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1135] = 1,
    ACTIONS(197), 6,
      ts_builtin_sym_end,
      aux_sym_identifier_token1,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_SLASH_SLASH,
  [1144] = 1,
    ACTIONS(199), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1153] = 1,
    ACTIONS(201), 6,
      ts_builtin_sym_end,
      aux_sym_identifier_token1,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_SLASH_SLASH,
  [1162] = 6,
    ACTIONS(5), 1,
      aux_sym_identifier_token1,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      sym_identifier,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    STATE(38), 1,
      sym_node,
    STATE(63), 1,
      aux_sym_document_repeat1,
  [1181] = 1,
    ACTIONS(205), 6,
      ts_builtin_sym_end,
      aux_sym_identifier_token1,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_SLASH_SLASH,
  [1190] = 1,
    ACTIONS(92), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1199] = 1,
    ACTIONS(207), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1208] = 1,
    ACTIONS(209), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1217] = 1,
    ACTIONS(211), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1226] = 6,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
    ACTIONS(215), 1,
      aux_sym_identifier_token1,
    STATE(17), 1,
      sym_identifier,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    STATE(38), 1,
      sym_node,
    STATE(63), 1,
      aux_sym_document_repeat1,
  [1245] = 1,
    ACTIONS(218), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1254] = 1,
    ACTIONS(132), 6,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
      anon_sym_SLASH_SLASH,
  [1263] = 4,
    ACTIONS(220), 1,
      sym__digit,
    STATE(64), 1,
      sym__integer,
    STATE(72), 1,
      sym__sign,
    ACTIONS(222), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1277] = 5,
    ACTIONS(15), 1,
      sym__digit,
    ACTIONS(224), 1,
      anon_sym_0x,
    ACTIONS(226), 1,
      anon_sym_0o,
    ACTIONS(228), 1,
      anon_sym_0b,
    STATE(23), 1,
      sym__integer,
  [1293] = 3,
    ACTIONS(230), 1,
      sym__newline,
    ACTIONS(232), 1,
      aux_sym__single_line_comment_token1,
    STATE(68), 1,
      aux_sym__single_line_comment_repeat1,
  [1303] = 3,
    ACTIONS(235), 1,
      sym__newline,
    ACTIONS(237), 1,
      aux_sym__single_line_comment_token1,
    STATE(68), 1,
      aux_sym__single_line_comment_repeat1,
  [1313] = 3,
    ACTIONS(237), 1,
      aux_sym__single_line_comment_token1,
    ACTIONS(239), 1,
      sym__newline,
    STATE(68), 1,
      aux_sym__single_line_comment_repeat1,
  [1323] = 2,
    ACTIONS(220), 1,
      sym__digit,
    STATE(33), 1,
      sym__integer,
  [1330] = 2,
    ACTIONS(220), 1,
      sym__digit,
    STATE(53), 1,
      sym__integer,
  [1337] = 1,
    ACTIONS(241), 2,
      anon_sym_0,
      anon_sym_1,
  [1342] = 1,
    ACTIONS(243), 2,
      anon_sym_0,
      anon_sym_1,
  [1347] = 2,
    ACTIONS(245), 1,
      aux_sym__single_line_comment_token1,
    STATE(69), 1,
      aux_sym__single_line_comment_repeat1,
  [1354] = 1,
    ACTIONS(213), 2,
      ts_builtin_sym_end,
      aux_sym_identifier_token1,
  [1359] = 2,
    ACTIONS(220), 1,
      sym__digit,
    STATE(30), 1,
      sym__integer,
  [1366] = 2,
    ACTIONS(247), 1,
      aux_sym__single_line_comment_token1,
    STATE(70), 1,
      aux_sym__single_line_comment_repeat1,
  [1373] = 1,
    ACTIONS(249), 1,
      aux_sym__octal_token1,
  [1377] = 1,
    ACTIONS(251), 1,
      sym__hex_digit,
  [1381] = 1,
    ACTIONS(253), 1,
      anon_sym_EQ,
  [1385] = 1,
    ACTIONS(255), 1,
      aux_sym__octal_token1,
  [1389] = 1,
    ACTIONS(257), 1,
      sym__hex_digit,
  [1393] = 1,
    ACTIONS(259), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 65,
  [SMALL_STATE(4)] = 130,
  [SMALL_STATE(5)] = 184,
  [SMALL_STATE(6)] = 219,
  [SMALL_STATE(7)] = 246,
  [SMALL_STATE(8)] = 273,
  [SMALL_STATE(9)] = 316,
  [SMALL_STATE(10)] = 343,
  [SMALL_STATE(11)] = 370,
  [SMALL_STATE(12)] = 391,
  [SMALL_STATE(13)] = 412,
  [SMALL_STATE(14)] = 439,
  [SMALL_STATE(15)] = 460,
  [SMALL_STATE(16)] = 487,
  [SMALL_STATE(17)] = 522,
  [SMALL_STATE(18)] = 557,
  [SMALL_STATE(19)] = 576,
  [SMALL_STATE(20)] = 595,
  [SMALL_STATE(21)] = 614,
  [SMALL_STATE(22)] = 643,
  [SMALL_STATE(23)] = 660,
  [SMALL_STATE(24)] = 679,
  [SMALL_STATE(25)] = 698,
  [SMALL_STATE(26)] = 715,
  [SMALL_STATE(27)] = 732,
  [SMALL_STATE(28)] = 749,
  [SMALL_STATE(29)] = 766,
  [SMALL_STATE(30)] = 782,
  [SMALL_STATE(31)] = 798,
  [SMALL_STATE(32)] = 814,
  [SMALL_STATE(33)] = 830,
  [SMALL_STATE(34)] = 846,
  [SMALL_STATE(35)] = 862,
  [SMALL_STATE(36)] = 878,
  [SMALL_STATE(37)] = 894,
  [SMALL_STATE(38)] = 910,
  [SMALL_STATE(39)] = 928,
  [SMALL_STATE(40)] = 943,
  [SMALL_STATE(41)] = 958,
  [SMALL_STATE(42)] = 973,
  [SMALL_STATE(43)] = 988,
  [SMALL_STATE(44)] = 1003,
  [SMALL_STATE(45)] = 1021,
  [SMALL_STATE(46)] = 1039,
  [SMALL_STATE(47)] = 1048,
  [SMALL_STATE(48)] = 1057,
  [SMALL_STATE(49)] = 1070,
  [SMALL_STATE(50)] = 1079,
  [SMALL_STATE(51)] = 1098,
  [SMALL_STATE(52)] = 1107,
  [SMALL_STATE(53)] = 1126,
  [SMALL_STATE(54)] = 1135,
  [SMALL_STATE(55)] = 1144,
  [SMALL_STATE(56)] = 1153,
  [SMALL_STATE(57)] = 1162,
  [SMALL_STATE(58)] = 1181,
  [SMALL_STATE(59)] = 1190,
  [SMALL_STATE(60)] = 1199,
  [SMALL_STATE(61)] = 1208,
  [SMALL_STATE(62)] = 1217,
  [SMALL_STATE(63)] = 1226,
  [SMALL_STATE(64)] = 1245,
  [SMALL_STATE(65)] = 1254,
  [SMALL_STATE(66)] = 1263,
  [SMALL_STATE(67)] = 1277,
  [SMALL_STATE(68)] = 1293,
  [SMALL_STATE(69)] = 1303,
  [SMALL_STATE(70)] = 1313,
  [SMALL_STATE(71)] = 1323,
  [SMALL_STATE(72)] = 1330,
  [SMALL_STATE(73)] = 1337,
  [SMALL_STATE(74)] = 1342,
  [SMALL_STATE(75)] = 1347,
  [SMALL_STATE(76)] = 1354,
  [SMALL_STATE(77)] = 1359,
  [SMALL_STATE(78)] = 1366,
  [SMALL_STATE(79)] = 1373,
  [SMALL_STATE(80)] = 1377,
  [SMALL_STATE(81)] = 1381,
  [SMALL_STATE(82)] = 1385,
  [SMALL_STATE(83)] = 1389,
  [SMALL_STATE(84)] = 1393,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_space, 1),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__node_space, 1),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__node_space_repeat2, 2),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__node_space_repeat2, 2),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__node_space_repeat2, 1),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__node_space_repeat2, 1),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__node_space_repeat1, 2),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__node_space_repeat1, 2),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__node_space_repeat1, 2), SHIFT_REPEAT(9),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__node_space_repeat2, 2), SHIFT_REPEAT(45),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__escline, 3),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__escline, 3),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__single_line_comment, 3),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__single_line_comment, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__escline, 2),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__escline, 2),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_space, 2),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__node_space, 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__integer, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__integer, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__integer_repeat1, 2),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__integer_repeat1, 2), SHIFT_REPEAT(20),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_node_repeat1, 2),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_repeat1, 2), SHIFT_REPEAT(5),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_repeat1, 2), SHIFT_REPEAT(45),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__binary_repeat1, 2),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__binary_repeat1, 2), SHIFT_REPEAT(22),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binary, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binary, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binary, 4),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__hex_repeat1, 2),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__hex_repeat1, 2), SHIFT_REPEAT(29),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 3),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex, 3),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 4),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifier_repeat1, 2),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifier_repeat1, 2), SHIFT_REPEAT(34),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex, 4),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 1),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__octal, 3),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__octal, 4),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__octal, 2),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__octal_repeat1, 2),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__octal_repeat1, 2), SHIFT_REPEAT(43),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__node_space_repeat1, 2), SHIFT_REPEAT(48),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 5),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exponent, 3),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 2),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 4),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 3),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prop, 3),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(36),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exponent, 2),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__single_line_comment_repeat1, 2),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__single_line_comment_repeat1, 2), SHIFT_REPEAT(68),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [259] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_kdl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
