#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 80
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_SEMI = 1,
  anon_sym_EQ = 2,
  aux_sym_identifier_token1 = 3,
  anon_sym_DOT = 4,
  anon_sym_e = 5,
  anon_sym_E = 6,
  anon_sym__ = 7,
  sym__digit = 8,
  anon_sym_PLUS = 9,
  anon_sym_DASH = 10,
  anon_sym_0x = 11,
  sym__hex_digit = 12,
  anon_sym_0o = 13,
  aux_sym__octal_token1 = 14,
  aux_sym__octal_token2 = 15,
  anon_sym_0b = 16,
  anon_sym_0 = 17,
  anon_sym_1 = 18,
  anon_sym_false = 19,
  anon_sym_true = 20,
  sym_null = 21,
  sym__newline = 22,
  anon_sym_ = 23,
  sym__unicode_space = 24,
  anon_sym_BSLASH = 25,
  sym_document = 26,
  sym_node = 27,
  sym__node_prop_or_arg = 28,
  sym__node_space = 29,
  sym__node_terminator = 30,
  sym_prop = 31,
  sym_identifier = 32,
  sym_value = 33,
  sym_number = 34,
  sym__decimal = 35,
  sym__exponent = 36,
  sym__integer = 37,
  sym__sign = 38,
  sym__hex = 39,
  sym__octal = 40,
  sym__binary = 41,
  sym_boolean = 42,
  sym__linespace = 43,
  sym__ws = 44,
  sym__escline = 45,
  aux_sym_document_repeat1 = 46,
  aux_sym_document_repeat2 = 47,
  aux_sym_node_repeat1 = 48,
  aux_sym__node_space_repeat1 = 49,
  aux_sym__node_space_repeat2 = 50,
  aux_sym_identifier_repeat1 = 51,
  aux_sym__integer_repeat1 = 52,
  aux_sym__hex_repeat1 = 53,
  aux_sym__octal_repeat1 = 54,
  aux_sym__binary_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [aux_sym_identifier_token1] = "identifier_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_e] = "e",
  [anon_sym_E] = "E",
  [anon_sym__] = "_",
  [sym__digit] = "_digit",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_0x] = "0x",
  [sym__hex_digit] = "_hex_digit",
  [anon_sym_0o] = "0o",
  [aux_sym__octal_token1] = "_octal_token1",
  [aux_sym__octal_token2] = "_octal_token2",
  [anon_sym_0b] = "0b",
  [anon_sym_0] = "0",
  [anon_sym_1] = "1",
  [anon_sym_false] = "false",
  [anon_sym_true] = "true",
  [sym_null] = "null",
  [sym__newline] = "_newline",
  [anon_sym_] = "﻿",
  [sym__unicode_space] = "_unicode_space",
  [anon_sym_BSLASH] = "\\",
  [sym_document] = "document",
  [sym_node] = "node",
  [sym__node_prop_or_arg] = "_node_prop_or_arg",
  [sym__node_space] = "_node_space",
  [sym__node_terminator] = "_node_terminator",
  [sym_prop] = "prop",
  [sym_identifier] = "identifier",
  [sym_value] = "value",
  [sym_number] = "number",
  [sym__decimal] = "_decimal",
  [sym__exponent] = "_exponent",
  [sym__integer] = "_integer",
  [sym__sign] = "_sign",
  [sym__hex] = "_hex",
  [sym__octal] = "_octal",
  [sym__binary] = "_binary",
  [sym_boolean] = "boolean",
  [sym__linespace] = "_linespace",
  [sym__ws] = "_ws",
  [sym__escline] = "_escline",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_document_repeat2] = "document_repeat2",
  [aux_sym_node_repeat1] = "node_repeat1",
  [aux_sym__node_space_repeat1] = "_node_space_repeat1",
  [aux_sym__node_space_repeat2] = "_node_space_repeat2",
  [aux_sym_identifier_repeat1] = "identifier_repeat1",
  [aux_sym__integer_repeat1] = "_integer_repeat1",
  [aux_sym__hex_repeat1] = "_hex_repeat1",
  [aux_sym__octal_repeat1] = "_octal_repeat1",
  [aux_sym__binary_repeat1] = "_binary_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_E] = anon_sym_E,
  [anon_sym__] = anon_sym__,
  [sym__digit] = sym__digit,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_0x] = anon_sym_0x,
  [sym__hex_digit] = sym__hex_digit,
  [anon_sym_0o] = anon_sym_0o,
  [aux_sym__octal_token1] = aux_sym__octal_token1,
  [aux_sym__octal_token2] = aux_sym__octal_token2,
  [anon_sym_0b] = anon_sym_0b,
  [anon_sym_0] = anon_sym_0,
  [anon_sym_1] = anon_sym_1,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_true] = anon_sym_true,
  [sym_null] = sym_null,
  [sym__newline] = sym__newline,
  [anon_sym_] = anon_sym_,
  [sym__unicode_space] = sym__unicode_space,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [sym_document] = sym_document,
  [sym_node] = sym_node,
  [sym__node_prop_or_arg] = sym__node_prop_or_arg,
  [sym__node_space] = sym__node_space,
  [sym__node_terminator] = sym__node_terminator,
  [sym_prop] = sym_prop,
  [sym_identifier] = sym_identifier,
  [sym_value] = sym_value,
  [sym_number] = sym_number,
  [sym__decimal] = sym__decimal,
  [sym__exponent] = sym__exponent,
  [sym__integer] = sym__integer,
  [sym__sign] = sym__sign,
  [sym__hex] = sym__hex,
  [sym__octal] = sym__octal,
  [sym__binary] = sym__binary,
  [sym_boolean] = sym_boolean,
  [sym__linespace] = sym__linespace,
  [sym__ws] = sym__ws,
  [sym__escline] = sym__escline,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_document_repeat2] = aux_sym_document_repeat2,
  [aux_sym_node_repeat1] = aux_sym_node_repeat1,
  [aux_sym__node_space_repeat1] = aux_sym__node_space_repeat1,
  [aux_sym__node_space_repeat2] = aux_sym__node_space_repeat2,
  [aux_sym_identifier_repeat1] = aux_sym_identifier_repeat1,
  [aux_sym__integer_repeat1] = aux_sym__integer_repeat1,
  [aux_sym__hex_repeat1] = aux_sym__hex_repeat1,
  [aux_sym__octal_repeat1] = aux_sym__octal_repeat1,
  [aux_sym__binary_repeat1] = aux_sym__binary_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [sym__digit] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0x] = {
    .visible = true,
    .named = false,
  },
  [sym__hex_digit] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_0o] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__octal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__octal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_0b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [sym__unicode_space] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_node] = {
    .visible = true,
    .named = true,
  },
  [sym__node_prop_or_arg] = {
    .visible = false,
    .named = true,
  },
  [sym__node_space] = {
    .visible = false,
    .named = true,
  },
  [sym__node_terminator] = {
    .visible = false,
    .named = true,
  },
  [sym_prop] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym__decimal] = {
    .visible = false,
    .named = true,
  },
  [sym__exponent] = {
    .visible = false,
    .named = true,
  },
  [sym__integer] = {
    .visible = false,
    .named = true,
  },
  [sym__sign] = {
    .visible = false,
    .named = true,
  },
  [sym__hex] = {
    .visible = false,
    .named = true,
  },
  [sym__octal] = {
    .visible = false,
    .named = true,
  },
  [sym__binary] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym__linespace] = {
    .visible = false,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [sym__escline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_node_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__node_space_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__node_space_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__integer_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__hex_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__octal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__binary_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == ' ') ADVANCE(43);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '0') ADVANCE(36);
      if (lookahead == '1') ADVANCE(37);
      if (lookahead == ';') ADVANCE(15);
      if (lookahead == '=') ADVANCE(16);
      if (lookahead == 'E') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(44);
      if (lookahead == '_') ADVANCE(24);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead == 't') ADVANCE(19);
      if (lookahead == 65279) ADVANCE(42);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'F')) ADVANCE(30);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      if (('2' <= lookahead && lookahead <= '7')) ADVANCE(25);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == ' ') ADVANCE(43);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '0') ADVANCE(26);
      if (lookahead == ';') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(44);
      if (lookahead == 'f') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead == 't') ADVANCE(19);
      if (lookahead == 65279) ADVANCE(42);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == ' ') ADVANCE(43);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == ';') ADVANCE(15);
      if (lookahead == 'E') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(44);
      if (lookahead == '_') ADVANCE(24);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == 65279) ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == ' ') ADVANCE(43);
      if (lookahead == ';') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(44);
      if (lookahead == '_') ADVANCE(24);
      if (lookahead == 65279) ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == ' ') ADVANCE(43);
      if (lookahead == ';') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(44);
      if (lookahead == 65279) ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(33);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(40);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(6);
      END_STATE();
    case 11:
      if (lookahead == 'u') ADVANCE(5);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(32);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == ' ') ADVANCE(43);
      if (lookahead == '0') ADVANCE(35);
      if (lookahead == '1') ADVANCE(37);
      if (lookahead == ';') ADVANCE(15);
      if (lookahead == '=') ADVANCE(16);
      if (lookahead == '\\') ADVANCE(44);
      if (lookahead == '_') ADVANCE(24);
      if (lookahead == 65279) ADVANCE(42);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_E);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__digit);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__digit);
      if (lookahead == 'b') ADVANCE(34);
      if (lookahead == 'o') ADVANCE(31);
      if (lookahead == 'x') ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_0x);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__hex_digit);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_0o);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__octal_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym__octal_token2);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_0b);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_0);
      if (lookahead == 'o') ADVANCE(31);
      if (lookahead == 'x') ADVANCE(29);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_1);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__unicode_space);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 13},
  [17] = {.lex_state = 13},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 13},
  [24] = {.lex_state = 13},
  [25] = {.lex_state = 13},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 13},
  [29] = {.lex_state = 13},
  [30] = {.lex_state = 13},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 13},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 13},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 13},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 13},
  [39] = {.lex_state = 13},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 13},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 13},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 13},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 13},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 13},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 13},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 12},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 12},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [sym__digit] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_0x] = ACTIONS(1),
    [sym__hex_digit] = ACTIONS(1),
    [anon_sym_0o] = ACTIONS(1),
    [aux_sym__octal_token1] = ACTIONS(1),
    [aux_sym__octal_token2] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [anon_sym_1] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [sym__unicode_space] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(74),
    [sym_node] = STATE(34),
    [sym_identifier] = STATE(18),
    [sym__linespace] = STATE(23),
    [sym__ws] = STATE(23),
    [aux_sym_document_repeat1] = STATE(23),
    [aux_sym_document_repeat2] = STATE(16),
    [aux_sym_identifier_repeat1] = STATE(36),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_identifier_token1] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [anon_sym_] = ACTIONS(7),
    [sym__unicode_space] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(13), 1,
      sym__digit,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_0o,
    ACTIONS(21), 1,
      anon_sym_0b,
    ACTIONS(25), 1,
      sym_null,
    STATE(26), 1,
      sym__integer,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    STATE(63), 1,
      sym__node_terminator,
    STATE(67), 1,
      sym__sign,
    STATE(78), 1,
      sym_identifier,
    ACTIONS(9), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(15), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(23), 2,
      anon_sym_false,
      anon_sym_true,
    STATE(55), 2,
      sym_number,
      sym_boolean,
    STATE(61), 3,
      sym__node_prop_or_arg,
      sym_prop,
      sym_value,
    STATE(65), 4,
      sym__decimal,
      sym__hex,
      sym__octal,
      sym__binary,
  [61] = 17,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(13), 1,
      sym__digit,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_0o,
    ACTIONS(21), 1,
      anon_sym_0b,
    ACTIONS(25), 1,
      sym_null,
    STATE(26), 1,
      sym__integer,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    STATE(54), 1,
      sym__node_terminator,
    STATE(67), 1,
      sym__sign,
    STATE(78), 1,
      sym_identifier,
    ACTIONS(15), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(23), 2,
      anon_sym_false,
      anon_sym_true,
    ACTIONS(27), 2,
      anon_sym_SEMI,
      sym__newline,
    STATE(55), 2,
      sym_number,
      sym_boolean,
    STATE(61), 3,
      sym__node_prop_or_arg,
      sym_prop,
      sym_value,
    STATE(65), 4,
      sym__decimal,
      sym__hex,
      sym__octal,
      sym__binary,
  [122] = 15,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(13), 1,
      sym__digit,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_0o,
    ACTIONS(21), 1,
      anon_sym_0b,
    ACTIONS(25), 1,
      sym_null,
    STATE(26), 1,
      sym__integer,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    STATE(67), 1,
      sym__sign,
    STATE(78), 1,
      sym_identifier,
    ACTIONS(15), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(23), 2,
      anon_sym_false,
      anon_sym_true,
    STATE(55), 2,
      sym_number,
      sym_boolean,
    STATE(61), 3,
      sym__node_prop_or_arg,
      sym_prop,
      sym_value,
    STATE(65), 4,
      sym__decimal,
      sym__hex,
      sym__octal,
      sym__binary,
  [176] = 7,
    ACTIONS(35), 1,
      anon_sym_BSLASH,
    STATE(7), 1,
      sym__escline,
    STATE(10), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(31), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(33), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(9), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(29), 10,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
  [210] = 12,
    ACTIONS(13), 1,
      sym__digit,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_0o,
    ACTIONS(21), 1,
      anon_sym_0b,
    ACTIONS(25), 1,
      sym_null,
    STATE(26), 1,
      sym__integer,
    STATE(60), 1,
      sym_value,
    STATE(67), 1,
      sym__sign,
    ACTIONS(15), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(23), 2,
      anon_sym_false,
      anon_sym_true,
    STATE(55), 2,
      sym_number,
      sym_boolean,
    STATE(65), 4,
      sym__decimal,
      sym__hex,
      sym__octal,
      sym__binary,
  [253] = 4,
    ACTIONS(39), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(41), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(8), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(37), 11,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_BSLASH,
  [279] = 4,
    ACTIONS(33), 2,
      anon_sym_,
      sym__unicode_space,
    ACTIONS(45), 2,
      aux_sym_identifier_token1,
      sym__digit,
    STATE(9), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(43), 11,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_BSLASH,
  [305] = 4,
    ACTIONS(49), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(51), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(9), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
    ACTIONS(47), 11,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_BSLASH,
  [331] = 5,
    ACTIONS(35), 1,
      anon_sym_BSLASH,
    STATE(7), 1,
      sym__escline,
    STATE(14), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(56), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(54), 10,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
  [357] = 5,
    ACTIONS(35), 1,
      anon_sym_BSLASH,
    STATE(7), 1,
      sym__escline,
    STATE(14), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(31), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(29), 10,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
  [383] = 2,
    ACTIONS(60), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(58), 13,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [403] = 2,
    ACTIONS(64), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(62), 13,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [423] = 5,
    ACTIONS(66), 1,
      anon_sym_BSLASH,
    STATE(7), 1,
      sym__escline,
    STATE(14), 1,
      aux_sym__node_space_repeat2,
    ACTIONS(45), 2,
      aux_sym_identifier_token1,
      sym__digit,
    ACTIONS(43), 10,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_0o,
      anon_sym_0b,
      anon_sym_false,
      anon_sym_true,
      sym_null,
      sym__newline,
  [449] = 9,
    ACTIONS(35), 1,
      anon_sym_BSLASH,
    STATE(3), 1,
      sym__node_space,
    STATE(7), 1,
      sym__escline,
    STATE(11), 1,
      aux_sym__node_space_repeat2,
    STATE(20), 1,
      aux_sym_node_repeat1,
    STATE(63), 1,
      sym__node_terminator,
    ACTIONS(9), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(69), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(5), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
  [480] = 8,
    ACTIONS(5), 1,
      aux_sym_identifier_token1,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      aux_sym_document_repeat2,
    STATE(18), 1,
      sym_identifier,
    STATE(34), 1,
      sym_node,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(7), 3,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
    STATE(23), 3,
      sym__linespace,
      sym__ws,
      aux_sym_document_repeat1,
  [509] = 8,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 1,
      aux_sym_identifier_token1,
    STATE(17), 1,
      aux_sym_document_repeat2,
    STATE(18), 1,
      sym_identifier,
    STATE(34), 1,
      sym_node,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(78), 3,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
    STATE(23), 3,
      sym__linespace,
      sym__ws,
      aux_sym_document_repeat1,
  [538] = 9,
    ACTIONS(35), 1,
      anon_sym_BSLASH,
    STATE(2), 1,
      sym__node_space,
    STATE(7), 1,
      sym__escline,
    STATE(11), 1,
      aux_sym__node_space_repeat2,
    STATE(15), 1,
      aux_sym_node_repeat1,
    STATE(50), 1,
      sym__node_terminator,
    ACTIONS(69), 2,
      anon_sym_,
      sym__unicode_space,
    ACTIONS(81), 2,
      anon_sym_SEMI,
      sym__newline,
    STATE(5), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
  [569] = 3,
    STATE(19), 1,
      aux_sym__integer_repeat1,
    ACTIONS(85), 2,
      anon_sym__,
      sym__digit,
    ACTIONS(83), 8,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_e,
      anon_sym_E,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [587] = 8,
    ACTIONS(93), 1,
      anon_sym_BSLASH,
    STATE(4), 1,
      sym__node_space,
    STATE(7), 1,
      sym__escline,
    STATE(11), 1,
      aux_sym__node_space_repeat2,
    STATE(20), 1,
      aux_sym_node_repeat1,
    ACTIONS(88), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(90), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(5), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
  [615] = 3,
    STATE(22), 1,
      aux_sym__integer_repeat1,
    ACTIONS(98), 2,
      anon_sym__,
      sym__digit,
    ACTIONS(96), 8,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_e,
      anon_sym_E,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [633] = 3,
    STATE(19), 1,
      aux_sym__integer_repeat1,
    ACTIONS(102), 2,
      anon_sym__,
      sym__digit,
    ACTIONS(100), 8,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_e,
      anon_sym_E,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [651] = 6,
    ACTIONS(5), 1,
      aux_sym_identifier_token1,
    STATE(18), 1,
      sym_identifier,
    STATE(36), 1,
      aux_sym_identifier_repeat1,
    STATE(44), 1,
      sym_node,
    ACTIONS(104), 3,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
    STATE(32), 3,
      sym__linespace,
      sym__ws,
      aux_sym_document_repeat1,
  [674] = 3,
    STATE(28), 1,
      aux_sym__binary_repeat1,
    ACTIONS(108), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(106), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [690] = 3,
    STATE(29), 1,
      aux_sym__binary_repeat1,
    ACTIONS(112), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(110), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [706] = 4,
    ACTIONS(116), 1,
      anon_sym_DOT,
    STATE(57), 1,
      sym__exponent,
    ACTIONS(118), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(114), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [724] = 4,
    ACTIONS(122), 1,
      anon_sym_DOT,
    STATE(68), 1,
      sym__exponent,
    ACTIONS(118), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(120), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [742] = 3,
    STATE(30), 1,
      aux_sym__binary_repeat1,
    ACTIONS(126), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(124), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [758] = 3,
    STATE(30), 1,
      aux_sym__binary_repeat1,
    ACTIONS(126), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(106), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [774] = 3,
    STATE(30), 1,
      aux_sym__binary_repeat1,
    ACTIONS(130), 3,
      anon_sym__,
      anon_sym_0,
      anon_sym_1,
    ACTIONS(128), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [790] = 3,
    ACTIONS(135), 1,
      aux_sym_identifier_token1,
    STATE(31), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(133), 6,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [805] = 3,
    ACTIONS(138), 2,
      ts_builtin_sym_end,
      aux_sym_identifier_token1,
    ACTIONS(140), 3,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
    STATE(32), 3,
      sym__linespace,
      sym__ws,
      aux_sym_document_repeat1,
  [820] = 3,
    STATE(53), 1,
      sym__exponent,
    ACTIONS(118), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(143), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [835] = 3,
    ACTIONS(145), 2,
      ts_builtin_sym_end,
      aux_sym_identifier_token1,
    ACTIONS(147), 3,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
    STATE(39), 3,
      sym__linespace,
      sym__ws,
      aux_sym_document_repeat1,
  [850] = 3,
    STATE(37), 1,
      aux_sym__hex_repeat1,
    ACTIONS(152), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(150), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [865] = 3,
    ACTIONS(156), 1,
      aux_sym_identifier_token1,
    STATE(31), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(154), 6,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [880] = 3,
    STATE(37), 1,
      aux_sym__hex_repeat1,
    ACTIONS(160), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(158), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [895] = 2,
    STATE(32), 3,
      sym__linespace,
      sym__ws,
      aux_sym_document_repeat1,
    ACTIONS(163), 5,
      ts_builtin_sym_end,
      aux_sym_identifier_token1,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
  [908] = 2,
    STATE(32), 3,
      sym__linespace,
      sym__ws,
      aux_sym_document_repeat1,
    ACTIONS(73), 5,
      ts_builtin_sym_end,
      aux_sym_identifier_token1,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
  [921] = 3,
    STATE(43), 1,
      aux_sym__hex_repeat1,
    ACTIONS(167), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(165), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [936] = 3,
    STATE(35), 1,
      aux_sym__hex_repeat1,
    ACTIONS(171), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(169), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [951] = 3,
    STATE(51), 1,
      sym__exponent,
    ACTIONS(118), 2,
      anon_sym_e,
      anon_sym_E,
    ACTIONS(173), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [966] = 3,
    STATE(37), 1,
      aux_sym__hex_repeat1,
    ACTIONS(152), 2,
      anon_sym__,
      sym__hex_digit,
    ACTIONS(169), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [981] = 3,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      aux_sym_identifier_token1,
    ACTIONS(175), 3,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
    STATE(38), 3,
      sym__linespace,
      sym__ws,
      aux_sym_document_repeat1,
  [996] = 3,
    ACTIONS(180), 1,
      aux_sym__octal_token2,
    STATE(46), 1,
      aux_sym__octal_repeat1,
    ACTIONS(178), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1010] = 3,
    ACTIONS(184), 1,
      aux_sym__octal_token2,
    STATE(46), 1,
      aux_sym__octal_repeat1,
    ACTIONS(182), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1024] = 3,
    ACTIONS(189), 1,
      aux_sym__octal_token2,
    STATE(45), 1,
      aux_sym__octal_repeat1,
    ACTIONS(187), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1038] = 3,
    ACTIONS(193), 1,
      aux_sym__octal_token2,
    STATE(49), 1,
      aux_sym__octal_repeat1,
    ACTIONS(191), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1052] = 3,
    ACTIONS(180), 1,
      aux_sym__octal_token2,
    STATE(46), 1,
      aux_sym__octal_repeat1,
    ACTIONS(187), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1066] = 1,
    ACTIONS(195), 5,
      ts_builtin_sym_end,
      aux_sym_identifier_token1,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
  [1074] = 1,
    ACTIONS(143), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1082] = 3,
    ACTIONS(47), 1,
      sym__newline,
    ACTIONS(197), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(52), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
  [1094] = 1,
    ACTIONS(200), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1102] = 1,
    ACTIONS(202), 5,
      ts_builtin_sym_end,
      aux_sym_identifier_token1,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
  [1110] = 1,
    ACTIONS(204), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1118] = 1,
    ACTIONS(206), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1126] = 1,
    ACTIONS(120), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1134] = 4,
    ACTIONS(208), 1,
      sym__digit,
    STATE(62), 1,
      sym__integer,
    STATE(71), 1,
      sym__sign,
    ACTIONS(210), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1148] = 3,
    ACTIONS(212), 1,
      sym__newline,
    ACTIONS(214), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(64), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
  [1160] = 1,
    ACTIONS(216), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1168] = 1,
    ACTIONS(88), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1176] = 1,
    ACTIONS(218), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1184] = 1,
    ACTIONS(220), 5,
      ts_builtin_sym_end,
      aux_sym_identifier_token1,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
  [1192] = 3,
    ACTIONS(222), 1,
      sym__newline,
    ACTIONS(224), 2,
      anon_sym_,
      sym__unicode_space,
    STATE(52), 2,
      sym__ws,
      aux_sym__node_space_repeat1,
  [1204] = 1,
    ACTIONS(226), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1212] = 1,
    ACTIONS(228), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1220] = 5,
    ACTIONS(13), 1,
      sym__digit,
    ACTIONS(230), 1,
      anon_sym_0x,
    ACTIONS(232), 1,
      anon_sym_0o,
    ACTIONS(234), 1,
      anon_sym_0b,
    STATE(27), 1,
      sym__integer,
  [1236] = 1,
    ACTIONS(173), 5,
      anon_sym_SEMI,
      sym__newline,
      anon_sym_,
      sym__unicode_space,
      anon_sym_BSLASH,
  [1244] = 1,
    ACTIONS(236), 2,
      anon_sym_0,
      anon_sym_1,
  [1249] = 2,
    ACTIONS(208), 1,
      sym__digit,
    STATE(33), 1,
      sym__integer,
  [1256] = 2,
    ACTIONS(208), 1,
      sym__digit,
    STATE(66), 1,
      sym__integer,
  [1263] = 2,
    ACTIONS(208), 1,
      sym__digit,
    STATE(42), 1,
      sym__integer,
  [1270] = 1,
    ACTIONS(238), 2,
      anon_sym_0,
      anon_sym_1,
  [1275] = 1,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
  [1279] = 1,
    ACTIONS(242), 1,
      sym__hex_digit,
  [1283] = 1,
    ACTIONS(244), 1,
      aux_sym__octal_token1,
  [1287] = 1,
    ACTIONS(246), 1,
      sym__hex_digit,
  [1291] = 1,
    ACTIONS(248), 1,
      anon_sym_EQ,
  [1295] = 1,
    ACTIONS(250), 1,
      aux_sym__octal_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 61,
  [SMALL_STATE(4)] = 122,
  [SMALL_STATE(5)] = 176,
  [SMALL_STATE(6)] = 210,
  [SMALL_STATE(7)] = 253,
  [SMALL_STATE(8)] = 279,
  [SMALL_STATE(9)] = 305,
  [SMALL_STATE(10)] = 331,
  [SMALL_STATE(11)] = 357,
  [SMALL_STATE(12)] = 383,
  [SMALL_STATE(13)] = 403,
  [SMALL_STATE(14)] = 423,
  [SMALL_STATE(15)] = 449,
  [SMALL_STATE(16)] = 480,
  [SMALL_STATE(17)] = 509,
  [SMALL_STATE(18)] = 538,
  [SMALL_STATE(19)] = 569,
  [SMALL_STATE(20)] = 587,
  [SMALL_STATE(21)] = 615,
  [SMALL_STATE(22)] = 633,
  [SMALL_STATE(23)] = 651,
  [SMALL_STATE(24)] = 674,
  [SMALL_STATE(25)] = 690,
  [SMALL_STATE(26)] = 706,
  [SMALL_STATE(27)] = 724,
  [SMALL_STATE(28)] = 742,
  [SMALL_STATE(29)] = 758,
  [SMALL_STATE(30)] = 774,
  [SMALL_STATE(31)] = 790,
  [SMALL_STATE(32)] = 805,
  [SMALL_STATE(33)] = 820,
  [SMALL_STATE(34)] = 835,
  [SMALL_STATE(35)] = 850,
  [SMALL_STATE(36)] = 865,
  [SMALL_STATE(37)] = 880,
  [SMALL_STATE(38)] = 895,
  [SMALL_STATE(39)] = 908,
  [SMALL_STATE(40)] = 921,
  [SMALL_STATE(41)] = 936,
  [SMALL_STATE(42)] = 951,
  [SMALL_STATE(43)] = 966,
  [SMALL_STATE(44)] = 981,
  [SMALL_STATE(45)] = 996,
  [SMALL_STATE(46)] = 1010,
  [SMALL_STATE(47)] = 1024,
  [SMALL_STATE(48)] = 1038,
  [SMALL_STATE(49)] = 1052,
  [SMALL_STATE(50)] = 1066,
  [SMALL_STATE(51)] = 1074,
  [SMALL_STATE(52)] = 1082,
  [SMALL_STATE(53)] = 1094,
  [SMALL_STATE(54)] = 1102,
  [SMALL_STATE(55)] = 1110,
  [SMALL_STATE(56)] = 1118,
  [SMALL_STATE(57)] = 1126,
  [SMALL_STATE(58)] = 1134,
  [SMALL_STATE(59)] = 1148,
  [SMALL_STATE(60)] = 1160,
  [SMALL_STATE(61)] = 1168,
  [SMALL_STATE(62)] = 1176,
  [SMALL_STATE(63)] = 1184,
  [SMALL_STATE(64)] = 1192,
  [SMALL_STATE(65)] = 1204,
  [SMALL_STATE(66)] = 1212,
  [SMALL_STATE(67)] = 1220,
  [SMALL_STATE(68)] = 1236,
  [SMALL_STATE(69)] = 1244,
  [SMALL_STATE(70)] = 1249,
  [SMALL_STATE(71)] = 1256,
  [SMALL_STATE(72)] = 1263,
  [SMALL_STATE(73)] = 1270,
  [SMALL_STATE(74)] = 1275,
  [SMALL_STATE(75)] = 1279,
  [SMALL_STATE(76)] = 1283,
  [SMALL_STATE(77)] = 1287,
  [SMALL_STATE(78)] = 1291,
  [SMALL_STATE(79)] = 1295,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_space, 1),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__node_space, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__node_space_repeat2, 1),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__node_space_repeat2, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__node_space_repeat2, 2),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__node_space_repeat2, 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__node_space_repeat1, 2),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__node_space_repeat1, 2),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__node_space_repeat1, 2), SHIFT_REPEAT(9),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_space, 2),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__node_space, 2),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__escline, 2),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__escline, 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__escline, 3),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__escline, 3),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__node_space_repeat2, 2), SHIFT_REPEAT(59),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2), SHIFT_REPEAT(36),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2), SHIFT_REPEAT(23),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__integer_repeat1, 2),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__integer_repeat1, 2), SHIFT_REPEAT(19),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_node_repeat1, 2),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_repeat1, 2), SHIFT_REPEAT(5),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_repeat1, 2), SHIFT_REPEAT(59),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__integer, 1),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__integer, 2),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binary, 3),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binary, 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 2),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binary, 4),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__binary_repeat1, 2),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__binary_repeat1, 2), SHIFT_REPEAT(30),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifier_repeat1, 2),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifier_repeat1, 2), SHIFT_REPEAT(31),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(32),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 1),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 1), SHIFT_REPEAT(39),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex, 4),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__hex_repeat1, 2),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__hex_repeat1, 2), SHIFT_REPEAT(37),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 3),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex, 2),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex, 3),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 3),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2), SHIFT_REPEAT(38),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__octal, 4),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__octal_repeat1, 2),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__octal_repeat1, 2), SHIFT_REPEAT(46),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__octal, 3),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__octal, 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 2),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__node_space_repeat1, 2), SHIFT_REPEAT(52),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 5),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 4),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prop, 3),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exponent, 2),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 3),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exponent, 3),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [240] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_kdl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
